# -*- mode: ruby -*-
# vi: set ft=ruby :
nodes = [
    { :hostname   => 'infra0',
      :ip         => '10.0.1.10',
      :box        => 'bento/centos-7.3',
    }
]

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

$script = <<SCRIPT


if [[ $(cat /sys/class/net/enp0s8/operstate) != 'up' ]]; then
    service network restart
fi

function install_puppet() {
    rpm -Uhv https://yum.puppetlabs.com/puppetlabs-release-el-$(rpm --eval %rhel).noarch.rpm
    yum -y install puppet
}

which puppet || install_puppet

SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    nodes.each do |node|
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.box = node[:box]
            nodeconfig.vm.hostname = node[:hostname]
            nodeconfig.vm.network :private_network, ip: node[:ip]
            memory = node[:ram] ? node[:ram] : 256
            nodeconfig.vm.provider :virtualbox do |vb|
                vb.customize [
                                 'modifyvm', :id,
                                 '--cpuexecutioncap', '40',
                                 '--memory', memory.to_s,
                             ]

            end
        end
        config.vm.synced_folder '..', '/etcdb'
        if File.directory? '../../pyetcd'
            config.vm.synced_folder '../../pyetcd', '/pyetcd'
        end
    end

    config.vm.provision 'shell', inline: $script
    config.vm.provision :puppet do |puppet|
        puppet.environment_path = 'environment'
        puppet.environment = 'puppet'
    end
end
