# -*- mode: ruby -*-
# vi: set ft=ruby :
nodes = [
    { :hostname   => 'client',
      :ip         => '10.0.1.9',
      :box        => 'bento/centos-7.1',
    },
    { :hostname   => 'infra0',
      :ip         => '10.0.1.10',
      :box        => 'bento/centos-7.1',
    },
    { :hostname   => 'infra1',
      :ip         => '10.0.1.11',
      :box        => 'bento/centos-7.1',
    },
    { :hostname   => 'infra2',
      :ip         => '10.0.1.12',
      :box        => 'bento/centos-7.1',
    }
]

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

$script = <<SCRIPT
rpm -Uhv https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
yum -y install puppet
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    nodes.each do |node|
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.box = node[:box]
            nodeconfig.vm.hostname = node[:hostname]
            nodeconfig.vm.network :private_network, ip: node[:ip]
            memory = node[:ram] ? node[:ram] : 256
            nodeconfig.vm.provider :virtualbox do |vb|
                vb.customize [
                                 'modifyvm', :id,
                                 '--cpuexecutioncap', '40',
                                 '--memory', memory.to_s,
                             ]

            end
        end
        config.vm.synced_folder '..', '/pyetcd'
    end

    config.vm.provision 'shell', inline: $script
    config.vm.provision :puppet do |puppet|
        puppet.environment_path = 'environment'
        puppet.environment = 'puppet'
    end
end
